database:
  host: 127.0.0.1
  #host: localhost
  port: 5432
  username: postgres
  password: 123456
  database: i18n
constants:
  modifier: admin
  project_type: i18n
  branch_name: master

sync:
  path: E:\tighub\kvhub\packages\server\config\all_kv.json